export const homeObjOne = {
    objTwo: false,
    id:'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Me',
    headline: ['Passionate', <br/>, 'Inquiring',<br/>,'Dedicated'],
    description: ['Currently a Computing Science student at',<br/>, 'Simon Fraser University, with 8 months of professional experience.'],
    description2: 'Currently a Computing Science student at Simon Fraser University, with 8 months of professional experience.',
    buttonLabel: 'Skills',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    objTwo: true,
    id:'Skills',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Skills',
    headline: '',
    description: '',
    buttonLabel: 'Projects',
    imgStart: false,
    img: require('../../images/svg-4.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
}
// export const homeObjThree = {
//     objTwo: false,
//     id:'Projects',
//     lightBg: false,
//     lightText: true,
//     lightTextDesc: true,
//     topLine: 'About Me',
//     headline: 'Passionate Inquisitive Dedicated',
//     description: 'Currently a Computing Science student at Simon Fraser University, Member of SFU Competitive Programming Club.',
//     buttonLabel: 'Skills',
//     imgStart: false,
//     img: require('../../images/svg-1.svg').default,
//     alt: 'Car',
//     dark: true,
//     primary: true,
//     darkText: false,
// }